# Note: MSVC_VERSION and MSVC_TOOLSET_VERSION are the vcpkg build toolset
#       use the "client" visual studio version
set(SERVER_DEV_TARGET 2019)
if($ENV{VisualStudioVersion} VERSION_GREATER_EQUAL "17.0")
  set(SERVER_DEV_TARGET 2022)
endif($ENV{VisualStudioVersion} VERSION_GREATER_EQUAL "17.0")
if(EXISTS "D:/Local_libs/share/cmake/ZOldFramework")
  message(STATUS "Using Greisby's sandbox ZOldFramework")
#  message(STATUS "include D:/Local_libs/share/cmake/ZOldFramework/ZOldFrameworkConfig.cmake")
  include("D:/Local_libs/share/cmake/ZOldFramework/ZOldFrameworkConfig.cmake")
elseif(EXISTS "//Server-DEV/Development/Releases/MFC_VS${SERVER_DEV_TARGET}/share/cmake/ZOldFramework")
  message(STATUS "Using Server-DEV ZOldFramework")
#  message(STATUS "include //Server-DEV/Development/Releases/MFC_VS${SERVER_DEV_TARGET}/share/cmake/ZOldFramework/ZOldFrameworkConfig.cmake")
  include("//Server-DEV/Development/Releases/MFC_VS${SERVER_DEV_TARGET}/share/cmake/ZOldFramework/ZOldFrameworkConfig.cmake")
else()
  message(FATAL_ERROR "No cmake config file found in either D:\\Local_libs\\share\\cmake or \\\\Server-DEV\\Development\\Releases\\MFC_VS${SERVER_DEV_TARGET}\\share\\cmake")
  set(ZOldFramework_FOUND 0)
endif()
unset(SERVER_DEV_TARGET)
