# Note: MSVC_VERSION and MSVC_TOOLSET_VERSION are the vcpkg build toolset
#       use the "client" visual studio version
if(WIN32)
  set(SERVER_DEV_TARGET 2019)
  if($ENV{VisualStudioVersion} VERSION_GREATER_EQUAL "17.0")
    set(SERVER_DEV_TARGET 2022)
  endif($ENV{VisualStudioVersion} VERSION_GREATER_EQUAL "17.0")
  if(EXISTS "D:/Local_libs/share/cmake/ZFramework")
    message(STATUS "Using Greisby's sandbox ZFramework")
    include("D:/Local_libs/share/cmake/ZFramework/ZFrameworkConfig.cmake")
  elseif(EXISTS "//Server-DEV/Development/Releases/MFC_VS${SERVER_DEV_TARGET}/share/cmake/ZFramework")
    message(STATUS "Using Server-DEV ZFramework")
    include("//Server-DEV/Development/Releases/MFC_VS${SERVER_DEV_TARGET}/share/cmake/ZFramework/ZFrameworkConfig.cmake")
  else()
    message(FATAL_ERROR "No cmake config file found in either D:\\Local_libs\\share\\cmake , \\\\Server-DEV\\Development\\Releases\\MFC_VS${SERVER_DEV_TARGET}\\share\\cmake or /usr/local/Zenon-Media/share/cmake")
  endif()
  unset(SERVER_DEV_TARGET)
else(WIN32)
  if(EXISTS "/usr/local/Zenon-Media/share/cmake/ZFramework")
    message(STATUS "Using ZFramework in /usr/local/Zenon-Media")
    include("/usr/local/Zenon-Media/share/cmake/ZFramework/ZFrameworkConfig.cmake")
  else()
    message(FATAL_ERROR "No cmake config file found in /usr/local/Zenon-Media/share/cmake")
  endif()
endif(WIN32)
